[phases.setup]
nixPkgs = ['python311Full', 'nodejs']

[phases.install]
cmds = [
  "python3 -m ensurepip --upgrade",
  "python3 -m pip install --no-cache-dir -r requirements.txt"
]

[start]
cmd = "node index.js"
